version: '3.4'
services:
  db-mysql:
    image: mysql:5.7
    container_name:
      db-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=3kd^fo3sdlf-sld
    ports:
      - "3306:3306"
    volumes:
      - $PWD/data:/var/lib/mysql
