version: '3.4'
services:
  ssserver-all:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 
      ssserver-all
    volumes:
      - ./shadowsocks.json:/data/ss/shadowsocks.json
    restart: 
      always
    ports:
      - '3308:3308'
      - '3309:3309'
      - '3310:3310'
      - '3311:3311'
      - '3312:3312'
      - '3313:3313'
    entrypoint:
      - ssserver
      - -c
      - /data/ss/shadowsocks.json






