version: '3.4'
services:
  ssserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 
      ssserver
    volumes:
      - ./shadowsocks.json:/Gcpdata/shadowsocks/shadowsocks.json
    restart: 
      always
    ports:
      - '5191:5191'
    entrypoint:
      - ssserver
      - -c
      - /Gcpdata/shadowsocks/shadowsocks.json






